### ISSUE TITLE
will you release 'addChildAtIndex' to npm?

### ISSUE THREAD

**Issue by jonrahoi** [joaonuno/tree-model-js#20]
i'm coding to the documentation but it hasn't been pushed to npm yet.  Is there a reason it hasn't gone out?  or do I need to pull the new code directly?

**Comment by peterheard01** [comment]
I got a message about this. I wrote this function and as far as I know I just pushed it and Joaonuno pulled and merged it. Not sure if anyone else knows what Jon is asking?  I am not sure how stuff ends up on npm....

**Comment by jonrahoi** [comment]
this fixed it for me 

`npm install joaonuno/tree-model-js --save`

**Comment by joaonuno** [comment]
Sorry about that, will do it as soon, maybe this weekend.

**Comment by joaonuno** [comment]
Just published it to npm
