### ISSUE TITLE
addChildAtIndex fails if parentnode has no children

### ISSUE THREAD

**Issue by jonrahoi** [joaonuno/tree-model-js#21]
starting at index.js line 101:

```javascript
if (insertIndex === undefined) {
    self.model[self.config.childrenPropertyName].push(child.model);
    self.children.push(child);
} else {
    if (insertIndex < 0 || insertIndex >= self.children.length) {
      throw new Error('Invalid index.');
    }
    self.model[self.config.childrenPropertyName].splice(insertIndex, 0, child.model);
    self.children.splice(index, 0, child);
}
```
if you try to call `parentNode.addChildAtIndex(newChild, 0)` when parentNode doesn't have any children, it *should* simply push the new node onto children.  Instead, since insertIndex is 0, not undefined, it then sees that ` insertIndex >= self.children.length` (both are zero) and it throws an Error.

**Comment by jonrahoi** [comment]
i'll try to work up a pull req for this later if no one else has the time.  or am I wrong about this?

**Comment by joaonuno** [comment]
Cannot test it now. If you fix it then please share it. `addChildAtIndex` should only be used when you need to force an ordering that cannot be enforced by a comparator function.

**Comment by peterheard01** [comment]
add a unit test to recreate this condition jon and see if you can fix it, probably something I missed sorry!
