### ISSUE TITLE
TypeError: Cannot read property 'children' of undefined

### ISSUE THREAD

**Issue by maeishoj** [joaonuno/tree-model-js#24]
Hey there.

Great library again, it's really awesome!

I was wondering why I get the error in title on TreeModel.js:184.

All I do is traverse a tree and if a certain node matches some criteria that I set, I drop it.

my structure looks like this: 
![screen shot 2015-07-15 at 12 05 44](https://cloud.githubusercontent.com/assets/1631903/8696091/d553a2ca-2ae9-11e5-9026-b8a44c1d3fc8.png)

so when it reaches the node "manufacturing" it throws that error.

However It does remove the "Board of Directors" before that in the same fashion, without throwing that error, as you can see here I print out before I drop nodes:

![screen shot 2015-07-15 at 12 06 46](https://cloud.githubusercontent.com/assets/1631903/8696127/1644c0de-2aea-11e5-8f3f-b9678e15f811.png)

So, what I do is:

       root.walk({strategy: 'post'}, function(node) {
                if(!node.model.selected){
                    if((node.children || []) && node.children.length < 1){
                        node.drop();
                        console.log("dropping ", node.model.title);
                    }
                }

            });

so I check if a node is not selected and it doesn't have any children, i wanna drop it.

Do you have an idea? Doesn't matter if I do "post or pre" if throws the same error.
I would appreciate your help! :)

**Comment by joaonuno** [comment]
Hi,

Dropping a node while walking the tree is not supported. See issues #5 and #19 for more details and a workaround.

**Comment by maeishoj** [comment]
@joaonuno  so basically the workaround would be for me to set a property on each of those nodes I wanna drop (say "toBeDeleted" = true) and then do 

    root.all( function (node) {
    return node.model.toBeDeleted === true;
}).forEach(function (node) {
  node.drop();
});

**Comment by joaonuno** [comment]
Yes, that would work. Or you can find all unselected nodes that don't have children and then drop them:

```js
root.all(function (node) {
  return !node.model.selected && node.children.length < 1;
}).forEach(function (node) {
  node.drop();
});
```

**Comment by maeishoj** [comment]
sure, it's my bad i didn't say exactly "ALL" the parameters that needs to be met.

So basically I have to select nodes and moving the selected nodes to a new array / object but maintaining their parents in the hierarchy. So not only I have to drop all nodes that are not selected and have no children (which is one case) but also all the nodes that are not selected and that do not have any children (at any point down the tree) selected.

So I guess my example would be "easier" to code from a logical level ? 

How about performance? Assuming the example was the simpler one like you posted, using your solution vs mine would be better performance wise?

**Comment by maeishoj** [comment]
Actually I may have a solution. The thing is i have the index of the last selected node (the deepest in the hierarchy) and doing this "SEEMS" to be working well. Of course I have to test several cases, but I think i got it:

root.all(function(node) {
                return (!node.model.selected && node.children.length < 1) || (!node.model.select && node.model.id > $scope.lastSelectedNode);
            }).forEach(function(node) {
                node.drop();
            });

**Comment by thankisk** [comment]
I believe this issue is already solved in latest version of JSTree, is there any documentation for this where it is mentioned that the issue is solved in latest version?
