### ISSUE TITLE
UglifyJS mangle-props option will break the code

### ISSUE THREAD

**Issue by yonatane** [joaonuno/tree-model-js#25]
Since walkStrategies are invoked by name and not by direct property access, and children are accessed by name (childrenPropertyName), obfuscating property names will break the code.
I, for example, am using the node package of TreeModel with browserify and then using UglifyJS to mangle properties. As a workaround I need to include all of the inner TreeModel properties as reserved_props of UglifyJS.

**Comment by joaonuno** [comment]
From uglifyjs docs https://github.com/mishoo/UglifyJS2#mangling-property-names---mangle-props:
> Note: this will probably break your code.

I guess it's safer not to use this flag at all.
