### ISSUE TITLE
Default argument for Node.prototype.all()

### ISSUE THREAD

**Issue by AljoschaMeyer** [joaonuno/tree-model-js#26]
Just a tiny suggestion for convenience: When calling node.all() without arguments, simply return all nodes, i.e. treat it as if a function that alays returns true was passed.
The same goes for node.first() I guess.

This is by no means necessary, it just popped into my head after I intuitively expected node.all() to 'just work'.

And also thanks for this package, it's pretty awesome.

**Comment by joaonuno** [comment]
I agree that would be an improvement, I'll do it soon.

Thank you for the kind words and your suggestion!

**Comment by joaonuno** [comment]
Fixed in release v1.0.1. Commit 75158eefbf1ffa0e14dbfab807b77ebd9ac5411a. Thanks!
