### ISSUE TITLE
Inconsistencies between node.children and nodemodel.children

### ISSUE THREAD

**Issue by AljoschaMeyer** [joaonuno/tree-model-js#27]
Hi again,

the implementation of node.drop() assumes that parent.children and parent.model.children are always sorted the same way.  This leads to node.drop to delete the correct entry in parent.children, but a wrong entry in parent.model.children, when that assumption isn't met.

The current implementation of addChildAtIndex does not guarantee that assumption. If I see this correctly, the line in question is [this one](https://github.com/joaonuno/tree-model-js/blob/master/index.js#L115), and changing `index` to `insertIndex` should fix it. Yay for typos!
At the very least, that change fixes the tests in my current project which failed before.

A quick fix would be very much appreciated :)

Even if it was only a typo, the unit tests for tree-js should however be updated to make sure adding a child keeps the order of node.children and node.model.children in sync, since this is critical for other functions to work correctly.

**Comment by joaonuno** [comment]
Thank you!
