### ISSUE TITLE
add filter function to tree data structure

### ISSUE THREAD

**Issue by brucou** [joaonuno/tree-model-js#31]
Given a tree, return a tree of the same structure made up of the objects returned by the callback which is executed at each node. If, however, at a given node the callback returns a falsy value, then the current node and all of its descendents will be pruned from the output tree.

Similar to `Array.filter`

Example : `node.filter(function (node, parent_node, index, root_node) {/*SOMETHING*/})`

NOTE : this is closely linked to this existing issue : https://github.com/joaonuno/tree-model-js/issues/22

**Comment by joaonuno** [comment]
Please see my comment on issue #30 

I already have a solution to the issue #22 that hopefully will cover the different traversal strategies but have not implemented it yet.

**Comment by brucou** [comment]
With a reducing traversal, stop at any level is relatively easy to implement : https://github.com/brucou/functional-rose-tree 

A function `pruneWhen` can additionally allow to remove part of the tree, based on a predicate. This is another indirect way to implement stopping conditions (if a part of the tree is removed, it can be traversed).
