### ISSUE TITLE
Import tree-model-js

### ISSUE THREAD

**Issue by tathagatbanerjee** [joaonuno/tree-model-js#38]
I'm trying to use tree-model with Node/React. Noob question, how do I do an import?

`import { TreeModel, Node } from 'tree-model';` does not seem to work? Thanks so much in advance.

**Comment by joaonuno** [comment]
Hi, I never tried to use the new module syntax, I'm not even sure if it's already available in node. Try to follow the example in the [readme](https://github.com/joaonuno/tree-model-js/blob/master/README.md) using the legacy require syntax.

**Comment by tathagatbanerjee** [comment]
ok - thanks so much. Appreciate the quick response. Thanks so much.
