### ISSUE TITLE
bower install problem

### ISSUE THREAD

**Issue by pillsilly** [joaonuno/tree-model-js#39]
I've seen tree-model.js in bower but when I try it
the installed package contains no dist folder.

I mean, if you use npm install,there'd be a 'dist' directory under 'node_modeules'
but if you use bower install,there'd be no such directory under 'bower_components',why?

**Comment by joaonuno** [comment]
Sorry, no plans to support other package managers besides npm. See #11

**Comment by pillsilly** [comment]
Noted and thanks for your reply.
