### ISSUE TITLE
put TreeModel.js

### ISSUE THREAD

**Issue by maruilian11** [joaonuno/tree-model-js#40]
Hi, I'm from cdnjs. Recently we want to add your lib to https://cdnjs.com, could you please consider adding `TreeModel.js` and `TreeModel.min.js` to git repo and adding git tags for each released version in the future because we use **git auto-update** to add each released version to cdnjs automatically, it can help us maintain your lib the latest version to your lib users.

https://github.com/cdnjs/cdnjs/issues/9138

**Comment by joaonuno** [comment]
Hi,

A few questions:

1. Where should I place those files so that [cdnjs.com]() can find them?
1. Should the name pattern of the browser ready files match any field of the `package.json`?
1. Would supporting [cdnjs.com]() mean that I have to make changes to the `package.json` as outlined here https://github.com/cdnjs/cdnjs/blob/master/documents/autoupdate.md?

Thanks

**Comment by maruilian11** [comment]
Hi @joaonuno ,

thanks for your reply,
1. you can put it in a `dist` folder, which helps us a lot.  
2. we will add a field `filename` in package.json point to the minified file.
you can name the file you want, but please don't add version number in its name. thanks.
3. no, the config can only mention in package.json in cdnjs, we will add it for you lib when sending the PR.

thank you :smiley:

**Comment by maruilian11** [comment]
@joaonuno thank you very much!
we also want to put old versions js and its minified file to cdnjs, could you please tell me where can I get old versions file? thanks!

**Comment by joaonuno** [comment]
You can download them [old.tar.gz](https://github.com/joaonuno/tree-model-js/files/629883/old.tar.gz).

I don't keep the old browser versions available for download. I ran the dist script for each tag to recreate these files for you. Hope it helps.

**Comment by maruilian11** [comment]
@joaonuno thank you so much!!!
