### ISSUE TITLE
How can I parse a data that have children as object?

### ISSUE THREAD

**Issue by saeidalidadi** [joaonuno/tree-model-js#41]
I have a tree model data already which the children are objects instead of arrays.
so how can I parse it?

**Comment by joaonuno** [comment]
Please share an example of the data and how you are trying to do it.

**Comment by saeidalidadi** [comment]
This is the data example as JSON:
{
  "type": "object",
  "children": {
    "email": {
      "type": "string",
      "flags": {
        "default": "alidadi@mail.com",
        "presence": "required"
      },
      "invalids": [
        ""
      ]
    },
    "name": {
      "type": "alternatives",
      "alternatives": [
        {
          "type": "string",
          "flags": {
            "default": "Saeid"
          },
          "invalids": [
            ""
          ]
        },
        {
          "type": "string",
          "flags": {
            "default": "Alidadi"
          },
          "invalids": [
            ""
          ]
        }
      ]
    },
    "phone": {
      "type": "number",
      "flags": {
        "default": "09339191848"
      },
      "invalids": [
        null,
        null
      ],
      "rules": [
        {
          "name": "integer"
        },
        {
          "name": "min",
          "arg": 1000
        }
      ]
    },
    "dob": {
      "type": "date",
      "flags": {
        "default": "2016-10-01",
        "presence": "required"
      }
    },
    "passport": {
      "type": "object",
      "flags": {
        "presence": "required"
      },
      "children": {
        "scan": {
          "type": "alternatives",
          "alternatives": [
            {
              "type": "string",
              "flags": {
                "default": "333",
                "presence": "required"
              },
              "invalids": [
                ""
              ]
            },
            {
              "type": "object",
              "children": {
                "small": {
                  "type": "array",
                  "flags": {
                    "sparse": false
                  },
                  "items": [
                    {
                      "type": "string",
                      "flags": {
                        "default": "/eye.jpg"
                      },
                      "invalids": [
                        ""
                      ]
                    }
                  ]
                }
              }
            }
          ]
        }
      }
    },
    "address": {
      "type": "string",
      "flags": {
        "default": "Tehran"
      },
      "invalids": [
        ""
      ]
    },
    "image_files": {
      "type": "array",
      "flags": {
        "sparse": false,
        "single": true
      },
      "items": [
        {
          "type": "object",
          "flags": {
            "allowUnknown": true
          },
          "children": {
            "hapi": {
              "type": "object",
              "flags": {
                "allowUnknown": true
              },
              "children": {
                "headers": {
                  "type": "object",
                  "flags": {
                    "allowUnknown": true
                  },
                  "children": {
                    "content-type": {
                      "type": "string",
                      "flags": {
                        "allowOnly": true
                      },
                      "valids": [
                        "image/jpeg"
                      ],
                      "invalids": [
                        ""
                      ]
                    }
                  }
                }
              }
            }
          }
        }
      ]
    }
  }
}
I have also `alternatives` and `array' that are like children in model

**Comment by joaonuno** [comment]
It is not possible to parse that data with this library. Maybe try another library which lets define a children getter function like this one https://www.npmjs.com/package/tree-traversal.

The reason this library doesn't support using a function to get the children is that, since it also does manipulation, it needs direct access to the children array.
