### ISSUE TITLE
Download TreeModel-min.js not avaible from WEB

### ISSUE THREAD

**Issue by carlesdalmases** [joaonuno/tree-model-js#43]
Hi,

The download from your webpage does not work
http://jnuno.com/tree-model-js/vendor/jnuno/TreeModel-min.js

**Comment by joaonuno** [comment]
Hi, I'm trying to fix it, not sure what's wrong, I've pushed the gh-pages branch twice with the updated files for the 1.0.5 release but somehow the page is full of 404's...

**Comment by richpressler** [comment]
Have you considered adding a build step that just copies the Node index.js and wraps it in the extra code that is needed for the browser version? This would always ensure an up-to-date version for the browser. This is part suggestion and part learning for me. I've only been professionally using JS (Node and Angular) for about a year and that would be my first thought but it may be a newbie one. Let me know what you think as I'd be happy to PR it if that works.

**Comment by richpressler** [comment]
Ignore that - after seeing your current setup what I suggested is kind of a moot point. Spoke before looking

**Comment by joaonuno** [comment]
This is now fixed. It was an issue related to the new github jekill version that now ignores the `vendor` folder by default. Adding a .nojekyll file solved it.
