### ISSUE TITLE
Any suggestion on trees comparison?

### ISSUE THREAD

**Issue by luangch** [joaonuno/tree-model-js#45]
I want to do a tree grafting. What approach do you guys suggest. 

My idea is doing a step by step comparison inside tree walk.

**Comment by joaonuno** [comment]
Not sure I understand your goal. You mention both comparison and grafting. Check if this [answer](http://stackoverflow.com/questions/26308342/merging-two-trees-using-treemodel-js/26312627#26312627) helps you in any way.
