### ISSUE TITLE
Can't create a node in NodeJS

### ISSUE THREAD

**Issue by tsirolnik** [joaonuno/tree-model-js#46]
Well, when requiring tree-model we only get the TreeModel and we can't access Node.

**Comment by joaonuno** [comment]
Hi, you receive a `Node` when calling some `TreeModel` methods, not by creating it directly.

**Comment by tsirolnik** [comment]
How can I add a child if I don't have the Node constructor?

**Comment by joaonuno** [comment]
You can see an example [here](http://jnuno.com/tree-model-js/). `tree.parse` returns a node instance.

```js
// Parse the new node
node123 = tree.parse({id: 123, children: [{id: 1231}]});
// Add it to the parent
node12.addChild(node123);
```

**Comment by tsirolnik** [comment]
Got it, you can close the issue :)
