### ISSUE TITLE
Get Children

### ISSUE THREAD

**Issue by ArtDesignCreativeStudio** [joaonuno/tree-model-js#49]
Thanks for excellent work. 

I have a question - how can i get  all children elements of any node - maybe function getChildren() similar getPath()

Thanks!

**Comment by joaonuno** [comment]
Hi, you can use the children property on any node, `node.children` to get the array of child nodes.

**Comment by pie6k** [comment]
note `node.children` is not present in typescript definition

**Comment by ali-habibzadeh** [comment]
node.model isn't either. How do you get auto completion for node models?
