### ISSUE TITLE
What does 'context' mean?

### ISSUE THREAD

**Issue by jungalwala** [joaonuno/tree-model-js#53]
You state in the documentation:

> node.walk([options], action, [context])
> These functions can also take, as the last parameter, the context on which the action will be called.

What does context mean?  And how is it used?  I don't see any example or reference to it in any of your documentation.

**Comment by joaonuno** [comment]
Hi, I mean `this`: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this#Function_context
