### ISSUE TITLE
Hasn't been a release since types have been added

### ISSUE THREAD

**Issue by Cowbacca** [joaonuno/tree-model-js#54]
Hi there!  

We're trying to use tree-model with TypeScript, but it looks like there hasn't been a release since https://github.com/joaonuno/tree-model-js/pull/52 was merged.  We're currently installing direct from the Github commit to get around this (i.e. `"tree-model": "github:joaonuno/tree-model-js#d3ecc029165b5403442a3bd59ff451faf5656ba5"`) but it would be great if there was a release.

Thanks for all the work!
Angus

**Comment by joaonuno** [comment]
You're right, will do it as soon as I find the time.
