### ISSUE TITLE
Proposition of new method 'toArray' 

### ISSUE THREAD

**Issue by krzysztof-grzybek** [joaonuno/tree-model-js#56]
Hi! Thanks for nice tool ;)

Using this project I have sometimes the case when I need to do some kind of `map` or `reduce` operation on node and its descendants. Having method `Node.prototype.toArray`, would make it a lot easier. This method would accept `options` argument, in which strategy could be defined.

What do You think about that? I can make PR.

**Comment by joaonuno** [comment]
Hi, you can already use the method `all()` (without arguments to get an array.
