### ISSUE TITLE
Inorder traversal

### ISSUE THREAD

**Issue by bozzltron** [joaonuno/tree-model-js#59]
I am interested in using your module, but I am looking for inorder traversal.

https://en.wikipedia.org/wiki/Tree_traversal#In-order_(LNR)

**Comment by joaonuno** [comment]
Hi, I think in-order traversal is only meaningful for binary trees. This library is for tree structures with any number of children. It doesn't have the notion of left and right sub-trees.

**Comment by bozzltron** [comment]
That makes sense.  Thank you.  I am looking at https://www.npmjs.com/package/binarytree.
