### ISSUE TITLE
Deleting a tree without deleting it's children

### ISSUE THREAD

**Issue by derblitz** [joaonuno/tree-model-js#70]
Is it somehow possible to delete a node without (optionally) deleting its children? That means...
if a node looks like this:
1
-1.1
-1.1.1
-1.1.2
-1.1.3
-1.2

... and you delete 1.1, the tree should look like this:
1
-1.1.1
-1.1.2
-1.1.3
-1.2

**Comment by joaonuno** [comment]
No specific method for that but this should work:

```js
nodeToDrop.children.forEach(child => nodeToDrop.parent.addChildAtIndex(child, nodeToDrop.getIndex() + child.getIndex()))
nodeToDrop.drop()
```

**Comment by derblitz** [comment]
Thank you!!!!!
