### ISSUE TITLE
Why is there no documentation on assigning the tree to a html tag ?

### ISSUE THREAD

**Issue by numerical25** [joaonuno/tree-model-js#79]
Im looking at the documentation and I see all the actions and animations but I have no clue on assigning the tree to a div so I can actually see the Tree. Can someone point me in the right direction ? 

Thanks

**Comment by joaonuno** [comment]
This lib is just for the tree data structure manipulation, not the actual rendering. The lib demo site uses [D3.js](https://d3js.org/) for that.
