### ISSUE TITLE
Dynamically add child to nested node.

### ISSUE THREAD

**Issue by mrfy** [joaonuno/tree-model-js#96]
Hi, I'm using this library but what I find difficult to achieve is dynamic tree extend, e.g. adding children for node `id: 121` for example below:

```lang=js
const tree = treeModel.parse({
  id: 1,
  deps: [
    {
      id: 11,
      deps: [{ id: 111 }],
    },
    {
      id: 12,
      deps: [{ id: 121 }, { id: 122 }],
    },
  ],
});
```

I looked through the tests and examples and found nothing to guide me. How can this be done to finally achieve a new tree model, eg add node `id: 123` ? I mean, function named, eg. `.addChildForSpecificNode()` will be very helpful.

```lang=js
const tree = treeModel.parse({
  id: 1,
  deps: [
    {
      id: 11,
      deps: [{ id: 111 }],
    },
    {
      id: 12,
      deps: [{ id: 121, deps: [{ id: 123 }] }, { id: 122 }],
    },
  ],
});
```

**Comment by joaonuno** [comment]
Hi, you can use the `addChild` or `addChildAtIndex` for that.
Example:
```js
let node121 = tree.first(node => node.model.id === 121)
node121.addChild(treeModel.parse({id: 123}))
```
